### ISSUE TITLE
Costos-Alvaro y antonia 

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-3-practica-de-costos-sistematosaurias#2]
[PRACTICA 2 costos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-sistematosaurias/files/14323600/PRACTICA.2.costos.pdf)

**Comment by ToniDepp** [comment]
Portada: 25/25
Procedimiento: 20/25
Figuras, ilustraciones y fotografías: 17/25
Resultados y conclusiones: 22/25
84/100 = 16.8%/20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
